name: test & build suite
on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - main
jobs:
  validatees-suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: install npm modules
        run: |
          npm ci
      - name: lint code base
        run: |
          npm run lint
      - name: build code base
        run: |
          npm run build --if-present
      - name: run test suite
        run: |
          npm test
